# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


name: cap-osba-app
resources:
  containers:
  - container: mta
    image: 'ppiper/mta-archive-builder:latest'
    options: --user 0:0
  - container: cfcli
    image: 'ppiper/cf-cli'
    options: --user 0:0 --privileged


trigger:
- master

stages:
- stage: Build
  displayName: Build MTA for SAP Cloud Platform
  jobs:
    - job: build
      pool:
        vmImage: 'ubuntu-latest'
      container: mta
      steps:
        - bash: npm install
          displayName: npm install
        - bash: npm run build:mta
          displayName: Build MTA
        - bash: npx cds deploy
          displayName: Deploy CDS Artefacts
        - bash: npm test  
          displayName: Test CAP application
        - publish: $(System.DefaultWorkingDirectory)/mta_archives/.
          artifact: WebApp
          
- stage: Deploy
  displayName: Deployment to SAP Cloud Platform
  jobs:
    - job: deploy
      pool:
        vmImage: 'ubuntu-latest'
      container: cfcli
      steps:
        - download: current
          artifact: WebApp
        - bash: |
                  cf login -u "$(CF-USER)" -p "$(CF-PASSWORD)" -a "$(CF-API)" -o "$(CF-ORG)" -s "$(CF-SPACE)"
                  cf deploy $(Pipeline.Workspace)/WebApp/city-explorer-demo-app.mtar -f